# Generated by Django 4.0.2 on 2022-03-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'managed': True, 'ordering': ('timestamp', 'dev'), 'verbose_name_plural': 'Значения'},
        ),
        migrations.AlterIndexTogether(
            name='quality',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='quality',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterIndexTogether(
            name='quality',
            index_together={('timestamp', 'dev')},
        ),
    ]
