# Generated by Django 4.0.2 on 2022-03-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0002_alter_quality_options_alter_quality_index_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'managed': True, 'ordering': ('timestamp', 'dev'), 'verbose_name': 'Значение', 'verbose_name_plural': 'Значения атрибутов'},
        ),
    ]
