# Generated by Django 4.0.3 on 2022-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0003_alter_quality_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Метка'),
        ),
    ]
