# Generated by Django 4.0.3 on 2022-04-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0004_alter_quality_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'managed': True, 'ordering': ['-timestamp'], 'verbose_name': 'Значение', 'verbose_name_plural': 'Значения атрибутов'},
        ),
    ]
