# Generated by Django 4.0.3 on 2022-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0005_alter_quality_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='value',
            field=models.CharField(default=None, max_length=30, verbose_name='Значение'),
        ),
    ]
