# Generated by Django 4.0.2 on 2022-02-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы запросов',
                'db_table': 'querysets',
                'ordering': ['setname'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=40, verbose_name='Свойство')),
                ('qset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='request.queryset', verbose_name='Набор запросов')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'db_table': 'queries',
                'ordering': ('qset', 'attribute'),
                'managed': True,
                'unique_together': {('qset', 'attribute')},
                'index_together': {('qset', 'attribute')},
            },
        ),
    ]
