# Generated by Django 4.0.2 on 2022-02-27 06:22

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='req',
            field=models.CharField(default=0, max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^[A-Fa-f0-9]+$'), 'Enter a valid hex number ', 'Ошибка')], verbose_name='Запрос'),
            preserve_default=False,
        ),
    ]
