# Generated by Django 4.0.2 on 2022-02-27 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_query_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='req',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[A-Fa-f0-9]+$')], verbose_name='Запрос'),
        ),
    ]
