# Generated by Django 4.0.2 on 2022-02-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_query_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='handler',
            field=models.CharField(default=0, max_length=40, verbose_name='Обработчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='unit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Единица измерения'),
        ),
    ]
