# Generated by Django 4.0.2 on 2022-02-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_query_handler_query_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryset',
            name='fn',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Примечание'),
        ),
    ]
