# Generated by Django 4.0.3 on 2022-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_query_fn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='unit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ед. изм.'),
        ),
    ]
