# Generated by Django 4.0.3 on 2022-03-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_query_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ИН'),
        ),
    ]
