# Generated by Django 4.0.3 on 2022-04-09 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_query_func_alter_query_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='req',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[A-Fa-f0-9]+$')], verbose_name='Данные'),
        ),
    ]
