# Generated by Django 4.0.3 on 2022-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_query_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='attribute',
            field=models.CharField(max_length=50, verbose_name='Свойство'),
        ),
    ]
