# Generated by Django 4.0.5 on 2022-06-09 09:07

import django.core.validators
from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_alter_query_qset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='func',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Fa-f0-9]+$'), request.models.validate_len_even], verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='query',
            name='req',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[A-Fa-f0-9]+$'), request.models.validate_len_even], verbose_name='Данные'),
        ),
    ]
