# Generated by Django 4.0.3 on 2022-05-22 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='addr',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Адрес'),
        ),
    ]
