# Generated by Django 4.0.3 on 2022-05-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_device_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mk',
            field=models.CharField(max_length=40, unique=True, verbose_name='Заводской №'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=40, verbose_name='Модель'),
        ),
    ]
