# Generated by Django 4.0.3 on 2022-05-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_device_mk_alter_device_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hub',
            options={'managed': True, 'ordering': ('host', 'port'), 'verbose_name': 'Контроллер', 'verbose_name_plural': 'Контроллеры УСПД'},
        ),
        migrations.AlterField(
            model_name='device',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.hub', verbose_name='Контроллер'),
        ),
    ]
