# Generated by Django 4.0.5 on 2022-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_hub_options_alter_device_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='baudrate',
            field=models.PositiveIntegerField(choices=[(2400, '2400'), (4800, '4800'), (9600, '9600'), (19200, '19200'), (38400, '38400'), (57600, '57600'), (115200, '115200')], null=True, verbose_name='Скорость бит/с'),
        ),
        migrations.AddField(
            model_name='device',
            name='bytesize',
            field=models.PositiveSmallIntegerField(choices=[(7, '7'), (8, '8')], null=True, verbose_name='Длина слова бит'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_portforwarding',
            field=models.BooleanField(default=False, verbose_name='Проброс порта'),
        ),
        migrations.AddField(
            model_name='device',
            name='parity',
            field=models.CharField(choices=[('N', 'Нет'), ('E', 'Четный'), ('O', 'Нечетный')], max_length=1, null=True, verbose_name='Контроль четности'),
        ),
        migrations.AddField(
            model_name='device',
            name='stopbits',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], null=True, verbose_name='Стоповые биты'),
        ),
    ]
