# Generated by Django 4.0.5 on 2022-06-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_remove_device_serial_port_exchange_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='serial_port_exchange_parameters',
        ),
    ]
